server:
  port: 8087

spring:
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    password:
  security:
    user:
      name: hi
      password : 123

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

